#!/bin/bash
#PBS -A UQ-CAI
#PBS -l select=1:ncpus=12:mem=24GB:vmem=24GB,walltime=6:00:00
#PBS -N ashs_1tp_optimex
#PBS -V 
#set -x
source ~/.bashrc
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=12
export NSLOTS=12
export ASHS_ROOT=/gpfs1/scratch/90days/uqtshaw/ashs-fastashs_beta
preprocessing_dir=/30days/uqtshaw/optimex/${SUBJNAME}
#where the data lives
out_dir=/30days/uqtshaw/optimex/derivatives/LASHiS/${SUBJNAME}/${SUBJNAME}
mkdir -p ${out_dir}
cd ${out_dir}
#Do LASHiS 
$ASHS_ROOT/bin/ashs_main.sh \
    -a /30days/uqtshaw/ashs_atlas_umcutrecht_7t_20170810/ \
    -g ${preprocessing_dir}/${SUBJNAME}_ses-01_T1w_N4corrected_norm_preproc.nii.gz \
    -f ${preprocessing_dir}/${SUBJNAME}_ses-01_T2w_NlinMoCo_res-iso.3_N4corrected_denoised_brain_preproc.nii.gz \
    -w "${out_dir}" 